config/routes.rb
Analytics3::Application.routes.draw do
  resources :listings

  get "home" => "pages#home"
  get "about" => "pages#about"
  get "pages" => "pages#contact"

  root 'listings#index'

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base

	if Rails.env.development?
		has_attached_file :image, :styles => { :thumb => "150x150>" }, :default_url => "missing.png"
	    validates_attachment_content_type :image, content_type: %w(image/jpeg image/jpg image/png)

	else
		has_attached_file :image, :styles => { :thumb => "150x150"},
    	:storage => :dropbox,
   	    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
   	    :path => ":style/id_:filename"
	end
		validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png) 
     	validates :job, :description, :location, :apply, :company, :url, :about, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:job, :description, :location, :apply, :company, :url, :about, :image, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<div class="page-header">
  <ul class="nav nav-pills pull-right">
    <li><%= link_to "About us", "/about" %></li>
  </ul>
  	  <h4><i class="fa fa-cube"></i> Work In Analytics</h4>
    

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Work In Analytics</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


<div class="container">

	<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

	<%= render 'layouts/header' %>
	<%= yield %>
</div>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing, :html => { :multipart => true } do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Your job listing will remain for 45 days. After 45 days your job listing will expire and be removed.</h4>
  <br/>
  <h3><b>1. Tell us about the position.</b></h3>
  <br/>

  <div class="form-group">
    <%= f.label "Job Title" %>
    <%= f.text_field :job, class: "form-control", autofocus: true, placeholder: "E.g Analytics Manager" %>
  </div>
  <div class="form-group">
    <%= f.label "Job Description" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Location" %>
    <%= f.text_field :location, class: "form-control", placeholder: "E.g London" %>
  </div>
  <div class="form-group">
    <%= f.label "How does the candidate apply" %>
    <%= f.text_field :apply, class: "form-control", placeholder: "E.g Send a C.V to neil@company.com" %>
  </div>

  <h3><b>2. Tell us about your company or recruitment agency</b></h3>
  <br/>
  <div class="form-group">
    <%= f.label "Your Company Name" %>
    <%= f.text_field :company, class: "form-control", placeholder: "E.g Google"  %>
  </div>
  <div class="form-group">
    <%= f.label "Upload Company Logo If You Want" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Tell Us About Your Business 25-30 chars max" %>
    <%= f.text_area :about, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Company Website" %>
    <%= f.text_field :url , class: "form-control", placeholder: "E.g http://www.google.com"  %>
  </div>

  <div class="form-group">
    <%= f.label "Email to send the reciept to" %>
    <%= f.text_field :email, class: "form-control", placeholder: "E.g john@google.com"  %>
  </div>



  <h3><b>3. Enter Your Credit Card Information</b></h3>

  
  
  <div class="form-group">
    <%= f.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="row">
    <div class="center">
        <h1>Find a Great Job in the Web Analytics Industry</h1>
          <h3>We only show open analytics jobs to make your search easy</h3>
          <h3>Follow us on Twitter <span class="emphasis">@WorkinAnalytics</span> </h3>
          <br>
           <%= link_to "Post a job Today: $169 for 45 days", new_listing_path , class: "btn btn-danger btn-lg" %>
    </div>
</div>
<br/>

<table class="table table-hover table-condensed">
    <% @listings.each do |listing| %>
      <tr>
        <td><h3><%= listing.company %></h3></td>
        <td><h3><%= link_to listing.job, listing %></h3></td>
        <td><h3><%= listing.created_at.strftime("%B %-d, %Y") %></h3></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/listings/new.html.erb
 

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class="blog-header">
        <h1 class="blog-title"><%= @listing.job %></h1>
        <p class="lead blog-description"><b>Posted on</b> <%= @listing.created_at.strftime("%B %-d, %Y") %></p>
        <h4><%= @listing.company %></h4>
        <h4><%= @listing.location %></h4>
        <h4><%= link_to @listing.url, @listing.url %></h4> 
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <p class="blog-post-title"> <%= @listing.description %></p>
            
            <hr>
           
            <h4><b>How to Apply For This Position</b></h4>
            <p><%= @listing.apply %> </p>
          </div><!-- /.blog-post -->
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <%= image_tag @listing.image.url(:thumb) %>
            <h5>About</h5>
            <p><%= @listing.about %></p>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->


<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/pages/about.html.erb
<h1>About</h1>

<p>Work In Analytics is/are Neil Patel & Shyaam Deshmukh. Part of Analyst365 </p>

<p>We are data geeks and love the adrenalin rush of perusing and gleaning insights out of analytical data. We would like to help the data and analytics professional to search for their dream job, through Analyst 365, in the companies and technologies they admire. This is only the beginning, our lofty goal is to build a community of analytics professionals who give back to the community by sharing knowledge: open source projects, essential tips, tricks, best practices, etc.</p>

<p>Interested? Please feel free to join us in our geeky mission.</p>

Thanks,
Team Analyst 365

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>